name: test-sai-pipeline

on:
  workflow_dispatch:      # manual trigger
  push:
    paths:
      - 'aft-account-requests/**'
  pull_request:
    paths:
      - 'aft-account-requests/**'

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder:
          - test-sai-account          # add more folders if needed

    defaults:
      run:
        working-directory: ./aft-account-requests/${{ matrix.folder }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Format Check
        run: terraform
