name: Validate AFT Account Request

on:
  workflow_dispatch:  # ✅ enables manual run button
  push:
    paths:
      - 'aft-account-requests/**'
  pull_request:
    paths:
      - 'aft-account-requests/**'

jobs:
  validate-terraform:
    name: Validate AFT Terraform Config
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder:
          - test-sai-account  # ✅ update if you have more folders

    defaults:
      run:
        working-directory: ./aft-account-requests/${{ matrix.folder }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
