name: Validate AFT Account Request

on:
  push:
    paths:
      - 'aft-account-requests/**'
  pull_request:
    paths:
      - 'aft-account-requests/**'

jobs:
  validate-terraform:
    name: Validate AFT Terraform Config
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./aft-account-requests/test-sai-account

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Initialize Terraform
        run: terraform init -backend=false

      - name: Validate Terraform
        run: terraform validate

      - name: Format Check
        run: terraform fmt -check -recursive
