name: Deploy AFT Account Request

on:
  workflow_dispatch:      # manual trigger
  push:
    paths:
      - 'aft-account-requests/**'
  pull_request:
    paths:
      - 'aft-account-requests/**'

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder:
          - test-sai-account          # add more folders if needed

    defaults:
      run:
        working-directory: ./aft-account-requests/${{ matrix.folder }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Plan
        run: terraform plan

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # set your Control Tower home region here

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'   # only apply on manual runs!
        run: terraform apply -auto-approve
